name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cpdb-protein/
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.16"
          python-version: "3.12"
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
